// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_logs (
    organization_id,
    actor_user_id,
    entity_type,
    entity_id,
    action,
    summary,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, organization_id, actor_user_id, entity_type, entity_id, action, summary, metadata, occurred_at
`

type CreateActivityLogParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	ActorUserID    *uuid.UUID `json:"actor_user_id"`
	EntityType     string     `json:"entity_type"`
	EntityID       uuid.UUID  `json:"entity_id"`
	Action         string     `json:"action"`
	Summary        *string    `json:"summary"`
	Metadata       []byte     `json:"metadata"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.OrganizationID,
		arg.ActorUserID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Summary,
		arg.Metadata,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ActorUserID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Summary,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}

const listActivityLogsByEntity = `-- name: ListActivityLogsByEntity :many
SELECT id, organization_id, actor_user_id, entity_type, entity_id, action, summary, metadata, occurred_at
FROM activity_logs
WHERE organization_id = $1
  AND entity_type = $2
  AND entity_id = $3
ORDER BY occurred_at DESC
`

type ListActivityLogsByEntityParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EntityType     string    `json:"entity_type"`
	EntityID       uuid.UUID `json:"entity_id"`
}

func (q *Queries) ListActivityLogsByEntity(ctx context.Context, arg ListActivityLogsByEntityParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogsByEntity, arg.OrganizationID, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ActorUserID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Summary,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
