// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MembershipRole string

const (
	MembershipRoleOwner              MembershipRole = "owner"
	MembershipRoleAdmin              MembershipRole = "admin"
	MembershipRoleRequester          MembershipRole = "requester"
	MembershipRoleApprover           MembershipRole = "approver"
	MembershipRoleProcurementOfficer MembershipRole = "procurement_officer"
	MembershipRoleViewer             MembershipRole = "viewer"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole `json:"membership_role"`
	Valid          bool           `json:"valid"` // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

type MembershipStatus string

const (
	MembershipStatusInvited   MembershipStatus = "invited"
	MembershipStatusActive    MembershipStatus = "active"
	MembershipStatusSuspended MembershipStatus = "suspended"
	MembershipStatusRemoved   MembershipStatus = "removed"
)

func (e *MembershipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipStatus(s)
	case string:
		*e = MembershipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipStatus: %T", src)
	}
	return nil
}

type NullMembershipStatus struct {
	MembershipStatus MembershipStatus `json:"membership_status"`
	Valid            bool             `json:"valid"` // Valid is true if MembershipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipStatus), nil
}

type ProcurementRequestStatus string

const (
	ProcurementRequestStatusDraft     ProcurementRequestStatus = "draft"
	ProcurementRequestStatusSubmitted ProcurementRequestStatus = "submitted"
	ProcurementRequestStatusApproved  ProcurementRequestStatus = "approved"
	ProcurementRequestStatusRejected  ProcurementRequestStatus = "rejected"
	ProcurementRequestStatusCancelled ProcurementRequestStatus = "cancelled"
)

func (e *ProcurementRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProcurementRequestStatus(s)
	case string:
		*e = ProcurementRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProcurementRequestStatus: %T", src)
	}
	return nil
}

type NullProcurementRequestStatus struct {
	ProcurementRequestStatus ProcurementRequestStatus `json:"procurement_request_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if ProcurementRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProcurementRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProcurementRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProcurementRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProcurementRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProcurementRequestStatus), nil
}

type QuotationStatus string

const (
	QuotationStatusDraft     QuotationStatus = "draft"
	QuotationStatusSubmitted QuotationStatus = "submitted"
	QuotationStatusRejected  QuotationStatus = "rejected"
)

func (e *QuotationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuotationStatus(s)
	case string:
		*e = QuotationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for QuotationStatus: %T", src)
	}
	return nil
}

type NullQuotationStatus struct {
	QuotationStatus QuotationStatus `json:"quotation_status"`
	Valid           bool            `json:"valid"` // Valid is true if QuotationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuotationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.QuotationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuotationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuotationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuotationStatus), nil
}

type RfqStatus string

const (
	RfqStatusDraft     RfqStatus = "draft"
	RfqStatusPublished RfqStatus = "published"
	RfqStatusClosed    RfqStatus = "closed"
	RfqStatusEvaluated RfqStatus = "evaluated"
	RfqStatusAwarded   RfqStatus = "awarded"
	RfqStatusCancelled RfqStatus = "cancelled"
)

func (e *RfqStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RfqStatus(s)
	case string:
		*e = RfqStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RfqStatus: %T", src)
	}
	return nil
}

type NullRfqStatus struct {
	RfqStatus RfqStatus `json:"rfq_status"`
	Valid     bool      `json:"valid"` // Valid is true if RfqStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRfqStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RfqStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RfqStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRfqStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RfqStatus), nil
}

type VendorStatus string

const (
	VendorStatusActive   VendorStatus = "active"
	VendorStatusArchived VendorStatus = "archived"
)

func (e *VendorStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VendorStatus(s)
	case string:
		*e = VendorStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VendorStatus: %T", src)
	}
	return nil
}

type NullVendorStatus struct {
	VendorStatus VendorStatus `json:"vendor_status"`
	Valid        bool         `json:"valid"` // Valid is true if VendorStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVendorStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VendorStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VendorStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVendorStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VendorStatus), nil
}

type ActivityLog struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	ActorUserID    *uuid.UUID         `json:"actor_user_id"`
	EntityType     string             `json:"entity_type"`
	EntityID       uuid.UUID          `json:"entity_id"`
	Action         string             `json:"action"`
	Summary        *string            `json:"summary"`
	Metadata       []byte             `json:"metadata"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}

type Organization struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
}

type OrganizationMembership struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	UserID          uuid.UUID          `json:"user_id"`
	Role            MembershipRole     `json:"role"`
	Status          MembershipStatus   `json:"status"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
	InvitedAt       pgtype.Timestamptz `json:"invited_at"`
	ActivatedAt     pgtype.Timestamptz `json:"activated_at"`
	SuspendedAt     pgtype.Timestamptz `json:"suspended_at"`
	RemovedAt       pgtype.Timestamptz `json:"removed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ProcurementRequest struct {
	ID                   uuid.UUID                `json:"id"`
	OrganizationID       uuid.UUID                `json:"organization_id"`
	RequesterUserID      uuid.UUID                `json:"requester_user_id"`
	Title                string                   `json:"title"`
	Description          *string                  `json:"description"`
	Justification        *string                  `json:"justification"`
	Status               ProcurementRequestStatus `json:"status"`
	CurrencyCode         string                   `json:"currency_code"`
	EstimatedTotalAmount pgtype.Numeric           `json:"estimated_total_amount"`
	SubmittedAt          pgtype.Timestamptz       `json:"submitted_at"`
	SubmittedByUserID    *uuid.UUID               `json:"submitted_by_user_id"`
	ApprovedAt           pgtype.Timestamptz       `json:"approved_at"`
	ApprovedByUserID     *uuid.UUID               `json:"approved_by_user_id"`
	RejectedAt           pgtype.Timestamptz       `json:"rejected_at"`
	RejectedByUserID     *uuid.UUID               `json:"rejected_by_user_id"`
	DecisionComment      *string                  `json:"decision_comment"`
	CancelledAt          pgtype.Timestamptz       `json:"cancelled_at"`
	CancelledByUserID    *uuid.UUID               `json:"cancelled_by_user_id"`
	CreatedAt            pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz       `json:"updated_at"`
}

type ProcurementRequestItem struct {
	ID                   uuid.UUID          `json:"id"`
	OrganizationID       uuid.UUID          `json:"organization_id"`
	ProcurementRequestID uuid.UUID          `json:"procurement_request_id"`
	LineNumber           int32              `json:"line_number"`
	ItemName             string             `json:"item_name"`
	Description          *string            `json:"description"`
	Quantity             pgtype.Numeric     `json:"quantity"`
	Unit                 string             `json:"unit"`
	EstimatedUnitPrice   pgtype.Numeric     `json:"estimated_unit_price"`
	NeededByDate         pgtype.Date        `json:"needed_by_date"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Quotation struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	RfqID             uuid.UUID          `json:"rfq_id"`
	RfqVendorID       uuid.UUID          `json:"rfq_vendor_id"`
	Status            QuotationStatus    `json:"status"`
	CurrencyCode      string             `json:"currency_code"`
	LeadTimeDays      *int32             `json:"lead_time_days"`
	PaymentTerms      *string            `json:"payment_terms"`
	Notes             *string            `json:"notes"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	SubmittedByUserID *uuid.UUID         `json:"submitted_by_user_id"`
	RejectedAt        pgtype.Timestamptz `json:"rejected_at"`
	RejectedByUserID  *uuid.UUID         `json:"rejected_by_user_id"`
	RejectionReason   *string            `json:"rejection_reason"`
	CreatedByUserID   uuid.UUID          `json:"created_by_user_id"`
	UpdatedByUserID   *uuid.UUID         `json:"updated_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type QuotationItem struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	QuotationID    uuid.UUID          `json:"quotation_id"`
	RfqID          uuid.UUID          `json:"rfq_id"`
	RfqItemID      uuid.UUID          `json:"rfq_item_id"`
	LineNumber     int32              `json:"line_number"`
	ItemName       string             `json:"item_name"`
	Description    *string            `json:"description"`
	Quantity       pgtype.Numeric     `json:"quantity"`
	Unit           string             `json:"unit"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	DeliveryDays   *int32             `json:"delivery_days"`
	Notes          *string            `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Rfq struct {
	ID                   uuid.UUID          `json:"id"`
	OrganizationID       uuid.UUID          `json:"organization_id"`
	ProcurementRequestID uuid.UUID          `json:"procurement_request_id"`
	ReferenceNumber      *string            `json:"reference_number"`
	Title                string             `json:"title"`
	Description          *string            `json:"description"`
	Status               RfqStatus          `json:"status"`
	CreatedByUserID      uuid.UUID          `json:"created_by_user_id"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	ClosedAt             pgtype.Timestamptz `json:"closed_at"`
	EvaluatedAt          pgtype.Timestamptz `json:"evaluated_at"`
	CancelledAt          pgtype.Timestamptz `json:"cancelled_at"`
	CancelledByUserID    *uuid.UUID         `json:"cancelled_by_user_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type RfqAward struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	RfqID           uuid.UUID          `json:"rfq_id"`
	QuotationID     uuid.UUID          `json:"quotation_id"`
	AwardedByUserID uuid.UUID          `json:"awarded_by_user_id"`
	Reason          string             `json:"reason"`
	AwardedAt       pgtype.Timestamptz `json:"awarded_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type RfqItem struct {
	ID                  uuid.UUID          `json:"id"`
	OrganizationID      uuid.UUID          `json:"organization_id"`
	RfqID               uuid.UUID          `json:"rfq_id"`
	SourceRequestItemID *uuid.UUID         `json:"source_request_item_id"`
	LineNumber          int32              `json:"line_number"`
	ItemName            string             `json:"item_name"`
	Description         *string            `json:"description"`
	Quantity            pgtype.Numeric     `json:"quantity"`
	Unit                string             `json:"unit"`
	TargetDate          pgtype.Date        `json:"target_date"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type RfqVendor struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	RfqID            uuid.UUID          `json:"rfq_id"`
	VendorID         uuid.UUID          `json:"vendor_id"`
	AttachedByUserID uuid.UUID          `json:"attached_by_user_id"`
	AttachedAt       pgtype.Timestamptz `json:"attached_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	IsActive     bool               `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Vendor struct {
	ID              uuid.UUID          `json:"id"`
	OrganizationID  uuid.UUID          `json:"organization_id"`
	Name            string             `json:"name"`
	LegalName       *string            `json:"legal_name"`
	ContactName     *string            `json:"contact_name"`
	Email           *string            `json:"email"`
	Phone           *string            `json:"phone"`
	TaxIdentifier   *string            `json:"tax_identifier"`
	AddressLine1    *string            `json:"address_line1"`
	AddressLine2    *string            `json:"address_line2"`
	City            *string            `json:"city"`
	StateRegion     *string            `json:"state_region"`
	PostalCode      *string            `json:"postal_code"`
	Country         *string            `json:"country"`
	Notes           *string            `json:"notes"`
	Status          VendorStatus       `json:"status"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
	UpdatedByUserID *uuid.UUID         `json:"updated_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
