// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    name,
    slug,
    created_by_user_id
) VALUES (
    $1, $2, $3
)
RETURNING id, name, slug, created_by_user_id, created_at, updated_at, archived_at
`

type CreateOrganizationParams struct {
	Name            string    `json:"name"`
	Slug            string    `json:"slug"`
	CreatedByUserID uuid.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug, arg.CreatedByUserID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createOrganizationMembership = `-- name: CreateOrganizationMembership :one
INSERT INTO organization_memberships (
    organization_id,
    user_id,
    role,
    status,
    created_by_user_id,
    activated_at
) VALUES (
    $1, $2, $3, $4, $5,
    CASE WHEN $4 = 'active' THEN now() ELSE NULL END
)
RETURNING id, organization_id, user_id, role, status, created_by_user_id, invited_at, activated_at, suspended_at, removed_at, created_at, updated_at
`

type CreateOrganizationMembershipParams struct {
	OrganizationID  uuid.UUID        `json:"organization_id"`
	UserID          uuid.UUID        `json:"user_id"`
	Role            MembershipRole   `json:"role"`
	Status          MembershipStatus `json:"status"`
	CreatedByUserID uuid.UUID        `json:"created_by_user_id"`
}

func (q *Queries) CreateOrganizationMembership(ctx context.Context, arg CreateOrganizationMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, createOrganizationMembership,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
		arg.Status,
		arg.CreatedByUserID,
	)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedByUserID,
		&i.InvitedAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.RemovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, created_by_user_id, created_at, updated_at, archived_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, created_by_user_id, created_at, updated_at, archived_at
FROM organizations
WHERE lower(slug) = lower($1)
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, lower string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, lower)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getOrganizationMembership = `-- name: GetOrganizationMembership :one
SELECT id, organization_id, user_id, role, status, created_by_user_id, invited_at, activated_at, suspended_at, removed_at, created_at, updated_at
FROM organization_memberships
WHERE organization_id = $1
  AND user_id = $2
`

type GetOrganizationMembershipParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOrganizationMembership(ctx context.Context, arg GetOrganizationMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getOrganizationMembership, arg.OrganizationID, arg.UserID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedByUserID,
		&i.InvitedAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.RemovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationMemberships = `-- name: ListOrganizationMemberships :many
SELECT id, organization_id, user_id, role, status, created_by_user_id, invited_at, activated_at, suspended_at, removed_at, created_at, updated_at
FROM organization_memberships
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrganizationMemberships(ctx context.Context, organizationID uuid.UUID) ([]OrganizationMembership, error) {
	rows, err := q.db.Query(ctx, listOrganizationMemberships, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationMembership{}
	for rows.Next() {
		var i OrganizationMembership
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedByUserID,
			&i.InvitedAt,
			&i.ActivatedAt,
			&i.SuspendedAt,
			&i.RemovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE organization_memberships
SET
    role = $3,
    updated_at = now()
WHERE organization_id = $1
  AND user_id = $2
RETURNING id, organization_id, user_id, role, status, created_by_user_id, invited_at, activated_at, suspended_at, removed_at, created_at, updated_at
`

type UpdateMembershipRoleParams struct {
	OrganizationID uuid.UUID      `json:"organization_id"`
	UserID         uuid.UUID      `json:"user_id"`
	Role           MembershipRole `json:"role"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole, arg.OrganizationID, arg.UserID, arg.Role)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedByUserID,
		&i.InvitedAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.RemovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMembershipStatus = `-- name: UpdateMembershipStatus :one
UPDATE organization_memberships
SET
    status = $3,
    activated_at = CASE WHEN $3 = 'active' AND activated_at IS NULL THEN now() ELSE activated_at END,
    suspended_at = CASE WHEN $3 = 'suspended' THEN now() ELSE suspended_at END,
    removed_at = CASE WHEN $3 = 'removed' THEN now() ELSE removed_at END,
    updated_at = now()
WHERE organization_id = $1
  AND user_id = $2
RETURNING id, organization_id, user_id, role, status, created_by_user_id, invited_at, activated_at, suspended_at, removed_at, created_at, updated_at
`

type UpdateMembershipStatusParams struct {
	OrganizationID uuid.UUID        `json:"organization_id"`
	UserID         uuid.UUID        `json:"user_id"`
	Status         MembershipStatus `json:"status"`
}

func (q *Queries) UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipStatus, arg.OrganizationID, arg.UserID, arg.Status)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedByUserID,
		&i.InvitedAt,
		&i.ActivatedAt,
		&i.SuspendedAt,
		&i.RemovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
