// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: procurement_requests.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveProcurementRequest = `-- name: ApproveProcurementRequest :one
UPDATE procurement_requests
SET
    status = 'approved',
    approved_at = now(),
    approved_by_user_id = $3,
    decision_comment = $4,
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status = 'submitted'
RETURNING id, organization_id, requester_user_id, title, description, justification, status, currency_code, estimated_total_amount, submitted_at, submitted_by_user_id, approved_at, approved_by_user_id, rejected_at, rejected_by_user_id, decision_comment, cancelled_at, cancelled_by_user_id, created_at, updated_at
`

type ApproveProcurementRequestParams struct {
	OrganizationID   uuid.UUID  `json:"organization_id"`
	ID               uuid.UUID  `json:"id"`
	ApprovedByUserID *uuid.UUID `json:"approved_by_user_id"`
	DecisionComment  *string    `json:"decision_comment"`
}

func (q *Queries) ApproveProcurementRequest(ctx context.Context, arg ApproveProcurementRequestParams) (ProcurementRequest, error) {
	row := q.db.QueryRow(ctx, approveProcurementRequest,
		arg.OrganizationID,
		arg.ID,
		arg.ApprovedByUserID,
		arg.DecisionComment,
	)
	var i ProcurementRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RequesterUserID,
		&i.Title,
		&i.Description,
		&i.Justification,
		&i.Status,
		&i.CurrencyCode,
		&i.EstimatedTotalAmount,
		&i.SubmittedAt,
		&i.SubmittedByUserID,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.RejectedAt,
		&i.RejectedByUserID,
		&i.DecisionComment,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelProcurementRequest = `-- name: CancelProcurementRequest :one
UPDATE procurement_requests
SET
    status = 'cancelled',
    cancelled_at = now(),
    cancelled_by_user_id = $3,
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status IN ('draft', 'submitted')
RETURNING id, organization_id, requester_user_id, title, description, justification, status, currency_code, estimated_total_amount, submitted_at, submitted_by_user_id, approved_at, approved_by_user_id, rejected_at, rejected_by_user_id, decision_comment, cancelled_at, cancelled_by_user_id, created_at, updated_at
`

type CancelProcurementRequestParams struct {
	OrganizationID    uuid.UUID  `json:"organization_id"`
	ID                uuid.UUID  `json:"id"`
	CancelledByUserID *uuid.UUID `json:"cancelled_by_user_id"`
}

func (q *Queries) CancelProcurementRequest(ctx context.Context, arg CancelProcurementRequestParams) (ProcurementRequest, error) {
	row := q.db.QueryRow(ctx, cancelProcurementRequest, arg.OrganizationID, arg.ID, arg.CancelledByUserID)
	var i ProcurementRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RequesterUserID,
		&i.Title,
		&i.Description,
		&i.Justification,
		&i.Status,
		&i.CurrencyCode,
		&i.EstimatedTotalAmount,
		&i.SubmittedAt,
		&i.SubmittedByUserID,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.RejectedAt,
		&i.RejectedByUserID,
		&i.DecisionComment,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProcurementRequest = `-- name: CreateProcurementRequest :one
INSERT INTO procurement_requests (
    organization_id,
    requester_user_id,
    title,
    description,
    justification,
    currency_code,
    estimated_total_amount
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, organization_id, requester_user_id, title, description, justification, status, currency_code, estimated_total_amount, submitted_at, submitted_by_user_id, approved_at, approved_by_user_id, rejected_at, rejected_by_user_id, decision_comment, cancelled_at, cancelled_by_user_id, created_at, updated_at
`

type CreateProcurementRequestParams struct {
	OrganizationID       uuid.UUID      `json:"organization_id"`
	RequesterUserID      uuid.UUID      `json:"requester_user_id"`
	Title                string         `json:"title"`
	Description          *string        `json:"description"`
	Justification        *string        `json:"justification"`
	CurrencyCode         string         `json:"currency_code"`
	EstimatedTotalAmount pgtype.Numeric `json:"estimated_total_amount"`
}

func (q *Queries) CreateProcurementRequest(ctx context.Context, arg CreateProcurementRequestParams) (ProcurementRequest, error) {
	row := q.db.QueryRow(ctx, createProcurementRequest,
		arg.OrganizationID,
		arg.RequesterUserID,
		arg.Title,
		arg.Description,
		arg.Justification,
		arg.CurrencyCode,
		arg.EstimatedTotalAmount,
	)
	var i ProcurementRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RequesterUserID,
		&i.Title,
		&i.Description,
		&i.Justification,
		&i.Status,
		&i.CurrencyCode,
		&i.EstimatedTotalAmount,
		&i.SubmittedAt,
		&i.SubmittedByUserID,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.RejectedAt,
		&i.RejectedByUserID,
		&i.DecisionComment,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProcurementRequestItem = `-- name: CreateProcurementRequestItem :one
INSERT INTO procurement_request_items (
    organization_id,
    procurement_request_id,
    line_number,
    item_name,
    description,
    quantity,
    unit,
    estimated_unit_price,
    needed_by_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, organization_id, procurement_request_id, line_number, item_name, description, quantity, unit, estimated_unit_price, needed_by_date, created_at, updated_at
`

type CreateProcurementRequestItemParams struct {
	OrganizationID       uuid.UUID      `json:"organization_id"`
	ProcurementRequestID uuid.UUID      `json:"procurement_request_id"`
	LineNumber           int32          `json:"line_number"`
	ItemName             string         `json:"item_name"`
	Description          *string        `json:"description"`
	Quantity             pgtype.Numeric `json:"quantity"`
	Unit                 string         `json:"unit"`
	EstimatedUnitPrice   pgtype.Numeric `json:"estimated_unit_price"`
	NeededByDate         pgtype.Date    `json:"needed_by_date"`
}

func (q *Queries) CreateProcurementRequestItem(ctx context.Context, arg CreateProcurementRequestItemParams) (ProcurementRequestItem, error) {
	row := q.db.QueryRow(ctx, createProcurementRequestItem,
		arg.OrganizationID,
		arg.ProcurementRequestID,
		arg.LineNumber,
		arg.ItemName,
		arg.Description,
		arg.Quantity,
		arg.Unit,
		arg.EstimatedUnitPrice,
		arg.NeededByDate,
	)
	var i ProcurementRequestItem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProcurementRequestID,
		&i.LineNumber,
		&i.ItemName,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.EstimatedUnitPrice,
		&i.NeededByDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProcurementRequestItem = `-- name: DeleteProcurementRequestItem :execrows
DELETE FROM procurement_request_items
WHERE organization_id = $1
  AND procurement_request_id = $2
  AND id = $3
`

type DeleteProcurementRequestItemParams struct {
	OrganizationID       uuid.UUID `json:"organization_id"`
	ProcurementRequestID uuid.UUID `json:"procurement_request_id"`
	ID                   uuid.UUID `json:"id"`
}

func (q *Queries) DeleteProcurementRequestItem(ctx context.Context, arg DeleteProcurementRequestItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProcurementRequestItem, arg.OrganizationID, arg.ProcurementRequestID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProcurementRequestByID = `-- name: GetProcurementRequestByID :one
SELECT id, organization_id, requester_user_id, title, description, justification, status, currency_code, estimated_total_amount, submitted_at, submitted_by_user_id, approved_at, approved_by_user_id, rejected_at, rejected_by_user_id, decision_comment, cancelled_at, cancelled_by_user_id, created_at, updated_at
FROM procurement_requests
WHERE organization_id = $1
  AND id = $2
`

type GetProcurementRequestByIDParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetProcurementRequestByID(ctx context.Context, arg GetProcurementRequestByIDParams) (ProcurementRequest, error) {
	row := q.db.QueryRow(ctx, getProcurementRequestByID, arg.OrganizationID, arg.ID)
	var i ProcurementRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RequesterUserID,
		&i.Title,
		&i.Description,
		&i.Justification,
		&i.Status,
		&i.CurrencyCode,
		&i.EstimatedTotalAmount,
		&i.SubmittedAt,
		&i.SubmittedByUserID,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.RejectedAt,
		&i.RejectedByUserID,
		&i.DecisionComment,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovalInboxRequests = `-- name: ListApprovalInboxRequests :many
SELECT id, organization_id, requester_user_id, title, description, justification, status, currency_code, estimated_total_amount, submitted_at, submitted_by_user_id, approved_at, approved_by_user_id, rejected_at, rejected_by_user_id, decision_comment, cancelled_at, cancelled_by_user_id, created_at, updated_at
FROM procurement_requests
WHERE organization_id = $1
  AND status = 'submitted'
ORDER BY submitted_at ASC NULLS LAST
`

func (q *Queries) ListApprovalInboxRequests(ctx context.Context, organizationID uuid.UUID) ([]ProcurementRequest, error) {
	rows, err := q.db.Query(ctx, listApprovalInboxRequests, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcurementRequest{}
	for rows.Next() {
		var i ProcurementRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RequesterUserID,
			&i.Title,
			&i.Description,
			&i.Justification,
			&i.Status,
			&i.CurrencyCode,
			&i.EstimatedTotalAmount,
			&i.SubmittedAt,
			&i.SubmittedByUserID,
			&i.ApprovedAt,
			&i.ApprovedByUserID,
			&i.RejectedAt,
			&i.RejectedByUserID,
			&i.DecisionComment,
			&i.CancelledAt,
			&i.CancelledByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcurementRequestItems = `-- name: ListProcurementRequestItems :many
SELECT id, organization_id, procurement_request_id, line_number, item_name, description, quantity, unit, estimated_unit_price, needed_by_date, created_at, updated_at
FROM procurement_request_items
WHERE organization_id = $1
  AND procurement_request_id = $2
ORDER BY line_number
`

type ListProcurementRequestItemsParams struct {
	OrganizationID       uuid.UUID `json:"organization_id"`
	ProcurementRequestID uuid.UUID `json:"procurement_request_id"`
}

func (q *Queries) ListProcurementRequestItems(ctx context.Context, arg ListProcurementRequestItemsParams) ([]ProcurementRequestItem, error) {
	rows, err := q.db.Query(ctx, listProcurementRequestItems, arg.OrganizationID, arg.ProcurementRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcurementRequestItem{}
	for rows.Next() {
		var i ProcurementRequestItem
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProcurementRequestID,
			&i.LineNumber,
			&i.ItemName,
			&i.Description,
			&i.Quantity,
			&i.Unit,
			&i.EstimatedUnitPrice,
			&i.NeededByDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcurementRequests = `-- name: ListProcurementRequests :many
SELECT id, organization_id, requester_user_id, title, description, justification, status, currency_code, estimated_total_amount, submitted_at, submitted_by_user_id, approved_at, approved_by_user_id, rejected_at, rejected_by_user_id, decision_comment, cancelled_at, cancelled_by_user_id, created_at, updated_at
FROM procurement_requests
WHERE organization_id = $1
  AND (
      $2::procurement_request_status IS NULL
      OR status = $2::procurement_request_status
  )
ORDER BY created_at DESC
`

type ListProcurementRequestsParams struct {
	OrganizationID uuid.UUID                    `json:"organization_id"`
	Status         NullProcurementRequestStatus `json:"status"`
}

func (q *Queries) ListProcurementRequests(ctx context.Context, arg ListProcurementRequestsParams) ([]ProcurementRequest, error) {
	rows, err := q.db.Query(ctx, listProcurementRequests, arg.OrganizationID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcurementRequest{}
	for rows.Next() {
		var i ProcurementRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RequesterUserID,
			&i.Title,
			&i.Description,
			&i.Justification,
			&i.Status,
			&i.CurrencyCode,
			&i.EstimatedTotalAmount,
			&i.SubmittedAt,
			&i.SubmittedByUserID,
			&i.ApprovedAt,
			&i.ApprovedByUserID,
			&i.RejectedAt,
			&i.RejectedByUserID,
			&i.DecisionComment,
			&i.CancelledAt,
			&i.CancelledByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectProcurementRequest = `-- name: RejectProcurementRequest :one
UPDATE procurement_requests
SET
    status = 'rejected',
    rejected_at = now(),
    rejected_by_user_id = $3,
    decision_comment = $4,
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status = 'submitted'
RETURNING id, organization_id, requester_user_id, title, description, justification, status, currency_code, estimated_total_amount, submitted_at, submitted_by_user_id, approved_at, approved_by_user_id, rejected_at, rejected_by_user_id, decision_comment, cancelled_at, cancelled_by_user_id, created_at, updated_at
`

type RejectProcurementRequestParams struct {
	OrganizationID   uuid.UUID  `json:"organization_id"`
	ID               uuid.UUID  `json:"id"`
	RejectedByUserID *uuid.UUID `json:"rejected_by_user_id"`
	DecisionComment  *string    `json:"decision_comment"`
}

func (q *Queries) RejectProcurementRequest(ctx context.Context, arg RejectProcurementRequestParams) (ProcurementRequest, error) {
	row := q.db.QueryRow(ctx, rejectProcurementRequest,
		arg.OrganizationID,
		arg.ID,
		arg.RejectedByUserID,
		arg.DecisionComment,
	)
	var i ProcurementRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RequesterUserID,
		&i.Title,
		&i.Description,
		&i.Justification,
		&i.Status,
		&i.CurrencyCode,
		&i.EstimatedTotalAmount,
		&i.SubmittedAt,
		&i.SubmittedByUserID,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.RejectedAt,
		&i.RejectedByUserID,
		&i.DecisionComment,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitProcurementRequest = `-- name: SubmitProcurementRequest :one
UPDATE procurement_requests
SET
    status = 'submitted',
    submitted_at = now(),
    submitted_by_user_id = $3,
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status = 'draft'
RETURNING id, organization_id, requester_user_id, title, description, justification, status, currency_code, estimated_total_amount, submitted_at, submitted_by_user_id, approved_at, approved_by_user_id, rejected_at, rejected_by_user_id, decision_comment, cancelled_at, cancelled_by_user_id, created_at, updated_at
`

type SubmitProcurementRequestParams struct {
	OrganizationID    uuid.UUID  `json:"organization_id"`
	ID                uuid.UUID  `json:"id"`
	SubmittedByUserID *uuid.UUID `json:"submitted_by_user_id"`
}

func (q *Queries) SubmitProcurementRequest(ctx context.Context, arg SubmitProcurementRequestParams) (ProcurementRequest, error) {
	row := q.db.QueryRow(ctx, submitProcurementRequest, arg.OrganizationID, arg.ID, arg.SubmittedByUserID)
	var i ProcurementRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RequesterUserID,
		&i.Title,
		&i.Description,
		&i.Justification,
		&i.Status,
		&i.CurrencyCode,
		&i.EstimatedTotalAmount,
		&i.SubmittedAt,
		&i.SubmittedByUserID,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.RejectedAt,
		&i.RejectedByUserID,
		&i.DecisionComment,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDraftProcurementRequest = `-- name: UpdateDraftProcurementRequest :one
UPDATE procurement_requests
SET
    title = $3,
    description = $4,
    justification = $5,
    currency_code = $6,
    estimated_total_amount = $7,
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status = 'draft'
RETURNING id, organization_id, requester_user_id, title, description, justification, status, currency_code, estimated_total_amount, submitted_at, submitted_by_user_id, approved_at, approved_by_user_id, rejected_at, rejected_by_user_id, decision_comment, cancelled_at, cancelled_by_user_id, created_at, updated_at
`

type UpdateDraftProcurementRequestParams struct {
	OrganizationID       uuid.UUID      `json:"organization_id"`
	ID                   uuid.UUID      `json:"id"`
	Title                string         `json:"title"`
	Description          *string        `json:"description"`
	Justification        *string        `json:"justification"`
	CurrencyCode         string         `json:"currency_code"`
	EstimatedTotalAmount pgtype.Numeric `json:"estimated_total_amount"`
}

func (q *Queries) UpdateDraftProcurementRequest(ctx context.Context, arg UpdateDraftProcurementRequestParams) (ProcurementRequest, error) {
	row := q.db.QueryRow(ctx, updateDraftProcurementRequest,
		arg.OrganizationID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Justification,
		arg.CurrencyCode,
		arg.EstimatedTotalAmount,
	)
	var i ProcurementRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RequesterUserID,
		&i.Title,
		&i.Description,
		&i.Justification,
		&i.Status,
		&i.CurrencyCode,
		&i.EstimatedTotalAmount,
		&i.SubmittedAt,
		&i.SubmittedByUserID,
		&i.ApprovedAt,
		&i.ApprovedByUserID,
		&i.RejectedAt,
		&i.RejectedByUserID,
		&i.DecisionComment,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProcurementRequestItem = `-- name: UpdateProcurementRequestItem :one
UPDATE procurement_request_items
SET
    item_name = $4,
    description = $5,
    quantity = $6,
    unit = $7,
    estimated_unit_price = $8,
    needed_by_date = $9,
    updated_at = now()
WHERE organization_id = $1
  AND procurement_request_id = $2
  AND id = $3
RETURNING id, organization_id, procurement_request_id, line_number, item_name, description, quantity, unit, estimated_unit_price, needed_by_date, created_at, updated_at
`

type UpdateProcurementRequestItemParams struct {
	OrganizationID       uuid.UUID      `json:"organization_id"`
	ProcurementRequestID uuid.UUID      `json:"procurement_request_id"`
	ID                   uuid.UUID      `json:"id"`
	ItemName             string         `json:"item_name"`
	Description          *string        `json:"description"`
	Quantity             pgtype.Numeric `json:"quantity"`
	Unit                 string         `json:"unit"`
	EstimatedUnitPrice   pgtype.Numeric `json:"estimated_unit_price"`
	NeededByDate         pgtype.Date    `json:"needed_by_date"`
}

func (q *Queries) UpdateProcurementRequestItem(ctx context.Context, arg UpdateProcurementRequestItemParams) (ProcurementRequestItem, error) {
	row := q.db.QueryRow(ctx, updateProcurementRequestItem,
		arg.OrganizationID,
		arg.ProcurementRequestID,
		arg.ID,
		arg.ItemName,
		arg.Description,
		arg.Quantity,
		arg.Unit,
		arg.EstimatedUnitPrice,
		arg.NeededByDate,
	)
	var i ProcurementRequestItem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProcurementRequestID,
		&i.LineNumber,
		&i.ItemName,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.EstimatedUnitPrice,
		&i.NeededByDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
