// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ApproveProcurementRequest(ctx context.Context, arg ApproveProcurementRequestParams) (ProcurementRequest, error)
	ArchiveVendor(ctx context.Context, arg ArchiveVendorParams) (Vendor, error)
	AttachVendorToRFQ(ctx context.Context, arg AttachVendorToRFQParams) (RfqVendor, error)
	CancelProcurementRequest(ctx context.Context, arg CancelProcurementRequestParams) (ProcurementRequest, error)
	CancelRFQ(ctx context.Context, arg CancelRFQParams) (Rfq, error)
	CloseRFQ(ctx context.Context, arg CloseRFQParams) (Rfq, error)
	CompareRFQQuotations(ctx context.Context, arg CompareRFQQuotationsParams) ([]CompareRFQQuotationsRow, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateOrganizationMembership(ctx context.Context, arg CreateOrganizationMembershipParams) (OrganizationMembership, error)
	CreateProcurementRequest(ctx context.Context, arg CreateProcurementRequestParams) (ProcurementRequest, error)
	CreateProcurementRequestItem(ctx context.Context, arg CreateProcurementRequestItemParams) (ProcurementRequestItem, error)
	CreateQuotation(ctx context.Context, arg CreateQuotationParams) (Quotation, error)
	CreateQuotationItem(ctx context.Context, arg CreateQuotationItemParams) (QuotationItem, error)
	CreateRFQ(ctx context.Context, arg CreateRFQParams) (Rfq, error)
	CreateRFQAward(ctx context.Context, arg CreateRFQAwardParams) (RfqAward, error)
	CreateRFQItem(ctx context.Context, arg CreateRFQItemParams) (RfqItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error)
	DeleteProcurementRequestItem(ctx context.Context, arg DeleteProcurementRequestItemParams) (int64, error)
	DeleteQuotationItem(ctx context.Context, arg DeleteQuotationItemParams) (int64, error)
	EvaluateRFQ(ctx context.Context, arg EvaluateRFQParams) (Rfq, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, lower string) (Organization, error)
	GetOrganizationMembership(ctx context.Context, arg GetOrganizationMembershipParams) (OrganizationMembership, error)
	GetProcurementRequestByID(ctx context.Context, arg GetProcurementRequestByIDParams) (ProcurementRequest, error)
	GetQuotationByID(ctx context.Context, arg GetQuotationByIDParams) (Quotation, error)
	GetRFQAwardByRFQ(ctx context.Context, arg GetRFQAwardByRFQParams) (RfqAward, error)
	GetRFQByID(ctx context.Context, arg GetRFQByIDParams) (Rfq, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetVendorByID(ctx context.Context, arg GetVendorByIDParams) (Vendor, error)
	ListActivityLogsByEntity(ctx context.Context, arg ListActivityLogsByEntityParams) ([]ActivityLog, error)
	ListApprovalInboxRequests(ctx context.Context, organizationID uuid.UUID) ([]ProcurementRequest, error)
	ListOrganizationMemberships(ctx context.Context, organizationID uuid.UUID) ([]OrganizationMembership, error)
	ListProcurementRequestItems(ctx context.Context, arg ListProcurementRequestItemsParams) ([]ProcurementRequestItem, error)
	ListProcurementRequests(ctx context.Context, arg ListProcurementRequestsParams) ([]ProcurementRequest, error)
	ListQuotationItems(ctx context.Context, arg ListQuotationItemsParams) ([]QuotationItem, error)
	ListQuotationsByRFQ(ctx context.Context, arg ListQuotationsByRFQParams) ([]ListQuotationsByRFQRow, error)
	ListRFQItems(ctx context.Context, arg ListRFQItemsParams) ([]RfqItem, error)
	ListRFQVendors(ctx context.Context, arg ListRFQVendorsParams) ([]ListRFQVendorsRow, error)
	ListRFQs(ctx context.Context, arg ListRFQsParams) ([]Rfq, error)
	ListUserOrganizations(ctx context.Context, userID uuid.UUID) ([]ListUserOrganizationsRow, error)
	ListVendors(ctx context.Context, arg ListVendorsParams) ([]Vendor, error)
	MarkRFQAwarded(ctx context.Context, arg MarkRFQAwardedParams) (Rfq, error)
	PublishRFQ(ctx context.Context, arg PublishRFQParams) (Rfq, error)
	RejectProcurementRequest(ctx context.Context, arg RejectProcurementRequestParams) (ProcurementRequest, error)
	RejectQuotation(ctx context.Context, arg RejectQuotationParams) (Quotation, error)
	RemoveVendorFromRFQ(ctx context.Context, arg RemoveVendorFromRFQParams) (int64, error)
	SearchVendors(ctx context.Context, arg SearchVendorsParams) ([]Vendor, error)
	SubmitProcurementRequest(ctx context.Context, arg SubmitProcurementRequestParams) (ProcurementRequest, error)
	SubmitQuotation(ctx context.Context, arg SubmitQuotationParams) (Quotation, error)
	UpdateDraftProcurementRequest(ctx context.Context, arg UpdateDraftProcurementRequestParams) (ProcurementRequest, error)
	UpdateDraftQuotation(ctx context.Context, arg UpdateDraftQuotationParams) (Quotation, error)
	UpdateDraftRFQ(ctx context.Context, arg UpdateDraftRFQParams) (Rfq, error)
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (OrganizationMembership, error)
	UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) (OrganizationMembership, error)
	UpdateProcurementRequestItem(ctx context.Context, arg UpdateProcurementRequestItemParams) (ProcurementRequestItem, error)
	UpdateQuotationItem(ctx context.Context, arg UpdateQuotationItemParams) (QuotationItem, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error)
}

var _ Querier = (*Queries)(nil)
