// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const compareRFQQuotations = `-- name: CompareRFQQuotations :many
SELECT
    q.id AS quotation_id,
    q.rfq_id,
    q.status,
    q.currency_code,
    q.lead_time_days,
    v.id AS vendor_id,
    v.name AS vendor_name,
    COALESCE(SUM(qi.quantity * qi.unit_price), 0)::NUMERIC(18, 2) AS total_amount,
    MIN(qi.delivery_days) AS fastest_item_delivery_days
FROM quotations AS q
JOIN rfq_vendors AS rv
    ON rv.rfq_id = q.rfq_id
   AND rv.id = q.rfq_vendor_id
JOIN vendors AS v
    ON v.organization_id = rv.organization_id
   AND v.id = rv.vendor_id
LEFT JOIN quotation_items AS qi
    ON qi.organization_id = q.organization_id
   AND qi.quotation_id = q.id
WHERE q.organization_id = $1
  AND q.rfq_id = $2
GROUP BY q.id, q.rfq_id, q.status, q.currency_code, q.lead_time_days, v.id, v.name
ORDER BY total_amount ASC, q.created_at ASC
`

type CompareRFQQuotationsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	RfqID          uuid.UUID `json:"rfq_id"`
}

type CompareRFQQuotationsRow struct {
	QuotationID             uuid.UUID       `json:"quotation_id"`
	RfqID                   uuid.UUID       `json:"rfq_id"`
	Status                  QuotationStatus `json:"status"`
	CurrencyCode            string          `json:"currency_code"`
	LeadTimeDays            *int32          `json:"lead_time_days"`
	VendorID                uuid.UUID       `json:"vendor_id"`
	VendorName              string          `json:"vendor_name"`
	TotalAmount             pgtype.Numeric  `json:"total_amount"`
	FastestItemDeliveryDays interface{}     `json:"fastest_item_delivery_days"`
}

func (q *Queries) CompareRFQQuotations(ctx context.Context, arg CompareRFQQuotationsParams) ([]CompareRFQQuotationsRow, error) {
	rows, err := q.db.Query(ctx, compareRFQQuotations, arg.OrganizationID, arg.RfqID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompareRFQQuotationsRow{}
	for rows.Next() {
		var i CompareRFQQuotationsRow
		if err := rows.Scan(
			&i.QuotationID,
			&i.RfqID,
			&i.Status,
			&i.CurrencyCode,
			&i.LeadTimeDays,
			&i.VendorID,
			&i.VendorName,
			&i.TotalAmount,
			&i.FastestItemDeliveryDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createQuotation = `-- name: CreateQuotation :one
INSERT INTO quotations (
    organization_id,
    rfq_id,
    rfq_vendor_id,
    currency_code,
    lead_time_days,
    payment_terms,
    notes,
    created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, organization_id, rfq_id, rfq_vendor_id, status, currency_code, lead_time_days, payment_terms, notes, submitted_at, submitted_by_user_id, rejected_at, rejected_by_user_id, rejection_reason, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type CreateQuotationParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	RfqID           uuid.UUID `json:"rfq_id"`
	RfqVendorID     uuid.UUID `json:"rfq_vendor_id"`
	CurrencyCode    string    `json:"currency_code"`
	LeadTimeDays    *int32    `json:"lead_time_days"`
	PaymentTerms    *string   `json:"payment_terms"`
	Notes           *string   `json:"notes"`
	CreatedByUserID uuid.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateQuotation(ctx context.Context, arg CreateQuotationParams) (Quotation, error) {
	row := q.db.QueryRow(ctx, createQuotation,
		arg.OrganizationID,
		arg.RfqID,
		arg.RfqVendorID,
		arg.CurrencyCode,
		arg.LeadTimeDays,
		arg.PaymentTerms,
		arg.Notes,
		arg.CreatedByUserID,
	)
	var i Quotation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RfqID,
		&i.RfqVendorID,
		&i.Status,
		&i.CurrencyCode,
		&i.LeadTimeDays,
		&i.PaymentTerms,
		&i.Notes,
		&i.SubmittedAt,
		&i.SubmittedByUserID,
		&i.RejectedAt,
		&i.RejectedByUserID,
		&i.RejectionReason,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuotationItem = `-- name: CreateQuotationItem :one
INSERT INTO quotation_items (
    organization_id,
    quotation_id,
    rfq_id,
    rfq_item_id,
    line_number,
    item_name,
    description,
    quantity,
    unit,
    unit_price,
    delivery_days,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, organization_id, quotation_id, rfq_id, rfq_item_id, line_number, item_name, description, quantity, unit, unit_price, delivery_days, notes, created_at, updated_at
`

type CreateQuotationItemParams struct {
	OrganizationID uuid.UUID      `json:"organization_id"`
	QuotationID    uuid.UUID      `json:"quotation_id"`
	RfqID          uuid.UUID      `json:"rfq_id"`
	RfqItemID      uuid.UUID      `json:"rfq_item_id"`
	LineNumber     int32          `json:"line_number"`
	ItemName       string         `json:"item_name"`
	Description    *string        `json:"description"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           string         `json:"unit"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	DeliveryDays   *int32         `json:"delivery_days"`
	Notes          *string        `json:"notes"`
}

func (q *Queries) CreateQuotationItem(ctx context.Context, arg CreateQuotationItemParams) (QuotationItem, error) {
	row := q.db.QueryRow(ctx, createQuotationItem,
		arg.OrganizationID,
		arg.QuotationID,
		arg.RfqID,
		arg.RfqItemID,
		arg.LineNumber,
		arg.ItemName,
		arg.Description,
		arg.Quantity,
		arg.Unit,
		arg.UnitPrice,
		arg.DeliveryDays,
		arg.Notes,
	)
	var i QuotationItem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.QuotationID,
		&i.RfqID,
		&i.RfqItemID,
		&i.LineNumber,
		&i.ItemName,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.UnitPrice,
		&i.DeliveryDays,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRFQAward = `-- name: CreateRFQAward :one
INSERT INTO rfq_awards (
    organization_id,
    rfq_id,
    quotation_id,
    awarded_by_user_id,
    reason
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, organization_id, rfq_id, quotation_id, awarded_by_user_id, reason, awarded_at, created_at
`

type CreateRFQAwardParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	RfqID           uuid.UUID `json:"rfq_id"`
	QuotationID     uuid.UUID `json:"quotation_id"`
	AwardedByUserID uuid.UUID `json:"awarded_by_user_id"`
	Reason          string    `json:"reason"`
}

func (q *Queries) CreateRFQAward(ctx context.Context, arg CreateRFQAwardParams) (RfqAward, error) {
	row := q.db.QueryRow(ctx, createRFQAward,
		arg.OrganizationID,
		arg.RfqID,
		arg.QuotationID,
		arg.AwardedByUserID,
		arg.Reason,
	)
	var i RfqAward
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RfqID,
		&i.QuotationID,
		&i.AwardedByUserID,
		&i.Reason,
		&i.AwardedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteQuotationItem = `-- name: DeleteQuotationItem :execrows
DELETE FROM quotation_items
WHERE organization_id = $1
  AND quotation_id = $2
  AND id = $3
`

type DeleteQuotationItemParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	QuotationID    uuid.UUID `json:"quotation_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) DeleteQuotationItem(ctx context.Context, arg DeleteQuotationItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteQuotationItem, arg.OrganizationID, arg.QuotationID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getQuotationByID = `-- name: GetQuotationByID :one
SELECT id, organization_id, rfq_id, rfq_vendor_id, status, currency_code, lead_time_days, payment_terms, notes, submitted_at, submitted_by_user_id, rejected_at, rejected_by_user_id, rejection_reason, created_by_user_id, updated_by_user_id, created_at, updated_at
FROM quotations
WHERE organization_id = $1
  AND id = $2
`

type GetQuotationByIDParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetQuotationByID(ctx context.Context, arg GetQuotationByIDParams) (Quotation, error) {
	row := q.db.QueryRow(ctx, getQuotationByID, arg.OrganizationID, arg.ID)
	var i Quotation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RfqID,
		&i.RfqVendorID,
		&i.Status,
		&i.CurrencyCode,
		&i.LeadTimeDays,
		&i.PaymentTerms,
		&i.Notes,
		&i.SubmittedAt,
		&i.SubmittedByUserID,
		&i.RejectedAt,
		&i.RejectedByUserID,
		&i.RejectionReason,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRFQAwardByRFQ = `-- name: GetRFQAwardByRFQ :one
SELECT id, organization_id, rfq_id, quotation_id, awarded_by_user_id, reason, awarded_at, created_at
FROM rfq_awards
WHERE organization_id = $1
  AND rfq_id = $2
`

type GetRFQAwardByRFQParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	RfqID          uuid.UUID `json:"rfq_id"`
}

func (q *Queries) GetRFQAwardByRFQ(ctx context.Context, arg GetRFQAwardByRFQParams) (RfqAward, error) {
	row := q.db.QueryRow(ctx, getRFQAwardByRFQ, arg.OrganizationID, arg.RfqID)
	var i RfqAward
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RfqID,
		&i.QuotationID,
		&i.AwardedByUserID,
		&i.Reason,
		&i.AwardedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listQuotationItems = `-- name: ListQuotationItems :many
SELECT id, organization_id, quotation_id, rfq_id, rfq_item_id, line_number, item_name, description, quantity, unit, unit_price, delivery_days, notes, created_at, updated_at
FROM quotation_items
WHERE organization_id = $1
  AND quotation_id = $2
ORDER BY line_number
`

type ListQuotationItemsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	QuotationID    uuid.UUID `json:"quotation_id"`
}

func (q *Queries) ListQuotationItems(ctx context.Context, arg ListQuotationItemsParams) ([]QuotationItem, error) {
	rows, err := q.db.Query(ctx, listQuotationItems, arg.OrganizationID, arg.QuotationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuotationItem{}
	for rows.Next() {
		var i QuotationItem
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.QuotationID,
			&i.RfqID,
			&i.RfqItemID,
			&i.LineNumber,
			&i.ItemName,
			&i.Description,
			&i.Quantity,
			&i.Unit,
			&i.UnitPrice,
			&i.DeliveryDays,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuotationsByRFQ = `-- name: ListQuotationsByRFQ :many
SELECT q.id, q.organization_id, q.rfq_id, q.rfq_vendor_id, q.status, q.currency_code, q.lead_time_days, q.payment_terms, q.notes, q.submitted_at, q.submitted_by_user_id, q.rejected_at, q.rejected_by_user_id, q.rejection_reason, q.created_by_user_id, q.updated_by_user_id, q.created_at, q.updated_at, v.name AS vendor_name
FROM quotations AS q
JOIN rfq_vendors AS rv
    ON rv.rfq_id = q.rfq_id
   AND rv.id = q.rfq_vendor_id
JOIN vendors AS v
    ON v.organization_id = rv.organization_id
   AND v.id = rv.vendor_id
WHERE q.organization_id = $1
  AND q.rfq_id = $2
ORDER BY q.created_at DESC
`

type ListQuotationsByRFQParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	RfqID          uuid.UUID `json:"rfq_id"`
}

type ListQuotationsByRFQRow struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	RfqID             uuid.UUID          `json:"rfq_id"`
	RfqVendorID       uuid.UUID          `json:"rfq_vendor_id"`
	Status            QuotationStatus    `json:"status"`
	CurrencyCode      string             `json:"currency_code"`
	LeadTimeDays      *int32             `json:"lead_time_days"`
	PaymentTerms      *string            `json:"payment_terms"`
	Notes             *string            `json:"notes"`
	SubmittedAt       pgtype.Timestamptz `json:"submitted_at"`
	SubmittedByUserID *uuid.UUID         `json:"submitted_by_user_id"`
	RejectedAt        pgtype.Timestamptz `json:"rejected_at"`
	RejectedByUserID  *uuid.UUID         `json:"rejected_by_user_id"`
	RejectionReason   *string            `json:"rejection_reason"`
	CreatedByUserID   uuid.UUID          `json:"created_by_user_id"`
	UpdatedByUserID   *uuid.UUID         `json:"updated_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	VendorName        string             `json:"vendor_name"`
}

func (q *Queries) ListQuotationsByRFQ(ctx context.Context, arg ListQuotationsByRFQParams) ([]ListQuotationsByRFQRow, error) {
	rows, err := q.db.Query(ctx, listQuotationsByRFQ, arg.OrganizationID, arg.RfqID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuotationsByRFQRow{}
	for rows.Next() {
		var i ListQuotationsByRFQRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RfqID,
			&i.RfqVendorID,
			&i.Status,
			&i.CurrencyCode,
			&i.LeadTimeDays,
			&i.PaymentTerms,
			&i.Notes,
			&i.SubmittedAt,
			&i.SubmittedByUserID,
			&i.RejectedAt,
			&i.RejectedByUserID,
			&i.RejectionReason,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VendorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectQuotation = `-- name: RejectQuotation :one
UPDATE quotations
SET
    status = 'rejected',
    rejected_at = now(),
    rejected_by_user_id = $3,
    rejection_reason = $4,
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status IN ('draft', 'submitted')
RETURNING id, organization_id, rfq_id, rfq_vendor_id, status, currency_code, lead_time_days, payment_terms, notes, submitted_at, submitted_by_user_id, rejected_at, rejected_by_user_id, rejection_reason, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type RejectQuotationParams struct {
	OrganizationID   uuid.UUID  `json:"organization_id"`
	ID               uuid.UUID  `json:"id"`
	RejectedByUserID *uuid.UUID `json:"rejected_by_user_id"`
	RejectionReason  *string    `json:"rejection_reason"`
}

func (q *Queries) RejectQuotation(ctx context.Context, arg RejectQuotationParams) (Quotation, error) {
	row := q.db.QueryRow(ctx, rejectQuotation,
		arg.OrganizationID,
		arg.ID,
		arg.RejectedByUserID,
		arg.RejectionReason,
	)
	var i Quotation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RfqID,
		&i.RfqVendorID,
		&i.Status,
		&i.CurrencyCode,
		&i.LeadTimeDays,
		&i.PaymentTerms,
		&i.Notes,
		&i.SubmittedAt,
		&i.SubmittedByUserID,
		&i.RejectedAt,
		&i.RejectedByUserID,
		&i.RejectionReason,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitQuotation = `-- name: SubmitQuotation :one
UPDATE quotations
SET
    status = 'submitted',
    submitted_at = now(),
    submitted_by_user_id = $3,
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status = 'draft'
RETURNING id, organization_id, rfq_id, rfq_vendor_id, status, currency_code, lead_time_days, payment_terms, notes, submitted_at, submitted_by_user_id, rejected_at, rejected_by_user_id, rejection_reason, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type SubmitQuotationParams struct {
	OrganizationID    uuid.UUID  `json:"organization_id"`
	ID                uuid.UUID  `json:"id"`
	SubmittedByUserID *uuid.UUID `json:"submitted_by_user_id"`
}

func (q *Queries) SubmitQuotation(ctx context.Context, arg SubmitQuotationParams) (Quotation, error) {
	row := q.db.QueryRow(ctx, submitQuotation, arg.OrganizationID, arg.ID, arg.SubmittedByUserID)
	var i Quotation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RfqID,
		&i.RfqVendorID,
		&i.Status,
		&i.CurrencyCode,
		&i.LeadTimeDays,
		&i.PaymentTerms,
		&i.Notes,
		&i.SubmittedAt,
		&i.SubmittedByUserID,
		&i.RejectedAt,
		&i.RejectedByUserID,
		&i.RejectionReason,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDraftQuotation = `-- name: UpdateDraftQuotation :one
UPDATE quotations
SET
    currency_code = $3,
    lead_time_days = $4,
    payment_terms = $5,
    notes = $6,
    updated_by_user_id = $7,
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status = 'draft'
RETURNING id, organization_id, rfq_id, rfq_vendor_id, status, currency_code, lead_time_days, payment_terms, notes, submitted_at, submitted_by_user_id, rejected_at, rejected_by_user_id, rejection_reason, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type UpdateDraftQuotationParams struct {
	OrganizationID  uuid.UUID  `json:"organization_id"`
	ID              uuid.UUID  `json:"id"`
	CurrencyCode    string     `json:"currency_code"`
	LeadTimeDays    *int32     `json:"lead_time_days"`
	PaymentTerms    *string    `json:"payment_terms"`
	Notes           *string    `json:"notes"`
	UpdatedByUserID *uuid.UUID `json:"updated_by_user_id"`
}

func (q *Queries) UpdateDraftQuotation(ctx context.Context, arg UpdateDraftQuotationParams) (Quotation, error) {
	row := q.db.QueryRow(ctx, updateDraftQuotation,
		arg.OrganizationID,
		arg.ID,
		arg.CurrencyCode,
		arg.LeadTimeDays,
		arg.PaymentTerms,
		arg.Notes,
		arg.UpdatedByUserID,
	)
	var i Quotation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RfqID,
		&i.RfqVendorID,
		&i.Status,
		&i.CurrencyCode,
		&i.LeadTimeDays,
		&i.PaymentTerms,
		&i.Notes,
		&i.SubmittedAt,
		&i.SubmittedByUserID,
		&i.RejectedAt,
		&i.RejectedByUserID,
		&i.RejectionReason,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuotationItem = `-- name: UpdateQuotationItem :one
UPDATE quotation_items
SET
    item_name = $4,
    description = $5,
    quantity = $6,
    unit = $7,
    unit_price = $8,
    delivery_days = $9,
    notes = $10,
    updated_at = now()
WHERE organization_id = $1
  AND quotation_id = $2
  AND id = $3
RETURNING id, organization_id, quotation_id, rfq_id, rfq_item_id, line_number, item_name, description, quantity, unit, unit_price, delivery_days, notes, created_at, updated_at
`

type UpdateQuotationItemParams struct {
	OrganizationID uuid.UUID      `json:"organization_id"`
	QuotationID    uuid.UUID      `json:"quotation_id"`
	ID             uuid.UUID      `json:"id"`
	ItemName       string         `json:"item_name"`
	Description    *string        `json:"description"`
	Quantity       pgtype.Numeric `json:"quantity"`
	Unit           string         `json:"unit"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	DeliveryDays   *int32         `json:"delivery_days"`
	Notes          *string        `json:"notes"`
}

func (q *Queries) UpdateQuotationItem(ctx context.Context, arg UpdateQuotationItemParams) (QuotationItem, error) {
	row := q.db.QueryRow(ctx, updateQuotationItem,
		arg.OrganizationID,
		arg.QuotationID,
		arg.ID,
		arg.ItemName,
		arg.Description,
		arg.Quantity,
		arg.Unit,
		arg.UnitPrice,
		arg.DeliveryDays,
		arg.Notes,
	)
	var i QuotationItem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.QuotationID,
		&i.RfqID,
		&i.RfqItemID,
		&i.LineNumber,
		&i.ItemName,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.UnitPrice,
		&i.DeliveryDays,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
