// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rfqs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachVendorToRFQ = `-- name: AttachVendorToRFQ :one
INSERT INTO rfq_vendors (
    organization_id,
    rfq_id,
    vendor_id,
    attached_by_user_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, organization_id, rfq_id, vendor_id, attached_by_user_id, attached_at, created_at
`

type AttachVendorToRFQParams struct {
	OrganizationID   uuid.UUID `json:"organization_id"`
	RfqID            uuid.UUID `json:"rfq_id"`
	VendorID         uuid.UUID `json:"vendor_id"`
	AttachedByUserID uuid.UUID `json:"attached_by_user_id"`
}

func (q *Queries) AttachVendorToRFQ(ctx context.Context, arg AttachVendorToRFQParams) (RfqVendor, error) {
	row := q.db.QueryRow(ctx, attachVendorToRFQ,
		arg.OrganizationID,
		arg.RfqID,
		arg.VendorID,
		arg.AttachedByUserID,
	)
	var i RfqVendor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RfqID,
		&i.VendorID,
		&i.AttachedByUserID,
		&i.AttachedAt,
		&i.CreatedAt,
	)
	return i, err
}

const cancelRFQ = `-- name: CancelRFQ :one
UPDATE rfqs
SET
    status = 'cancelled',
    cancelled_at = now(),
    cancelled_by_user_id = $3,
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status IN ('draft', 'published', 'closed', 'evaluated')
RETURNING id, organization_id, procurement_request_id, reference_number, title, description, status, created_by_user_id, published_at, closed_at, evaluated_at, cancelled_at, cancelled_by_user_id, created_at, updated_at
`

type CancelRFQParams struct {
	OrganizationID    uuid.UUID  `json:"organization_id"`
	ID                uuid.UUID  `json:"id"`
	CancelledByUserID *uuid.UUID `json:"cancelled_by_user_id"`
}

func (q *Queries) CancelRFQ(ctx context.Context, arg CancelRFQParams) (Rfq, error) {
	row := q.db.QueryRow(ctx, cancelRFQ, arg.OrganizationID, arg.ID, arg.CancelledByUserID)
	var i Rfq
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProcurementRequestID,
		&i.ReferenceNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedByUserID,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.EvaluatedAt,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeRFQ = `-- name: CloseRFQ :one
UPDATE rfqs
SET
    status = 'closed',
    closed_at = now(),
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status = 'published'
RETURNING id, organization_id, procurement_request_id, reference_number, title, description, status, created_by_user_id, published_at, closed_at, evaluated_at, cancelled_at, cancelled_by_user_id, created_at, updated_at
`

type CloseRFQParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) CloseRFQ(ctx context.Context, arg CloseRFQParams) (Rfq, error) {
	row := q.db.QueryRow(ctx, closeRFQ, arg.OrganizationID, arg.ID)
	var i Rfq
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProcurementRequestID,
		&i.ReferenceNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedByUserID,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.EvaluatedAt,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRFQ = `-- name: CreateRFQ :one
INSERT INTO rfqs (
    organization_id,
    procurement_request_id,
    reference_number,
    title,
    description,
    created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, organization_id, procurement_request_id, reference_number, title, description, status, created_by_user_id, published_at, closed_at, evaluated_at, cancelled_at, cancelled_by_user_id, created_at, updated_at
`

type CreateRFQParams struct {
	OrganizationID       uuid.UUID `json:"organization_id"`
	ProcurementRequestID uuid.UUID `json:"procurement_request_id"`
	ReferenceNumber      *string   `json:"reference_number"`
	Title                string    `json:"title"`
	Description          *string   `json:"description"`
	CreatedByUserID      uuid.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateRFQ(ctx context.Context, arg CreateRFQParams) (Rfq, error) {
	row := q.db.QueryRow(ctx, createRFQ,
		arg.OrganizationID,
		arg.ProcurementRequestID,
		arg.ReferenceNumber,
		arg.Title,
		arg.Description,
		arg.CreatedByUserID,
	)
	var i Rfq
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProcurementRequestID,
		&i.ReferenceNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedByUserID,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.EvaluatedAt,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRFQItem = `-- name: CreateRFQItem :one
INSERT INTO rfq_items (
    organization_id,
    rfq_id,
    source_request_item_id,
    line_number,
    item_name,
    description,
    quantity,
    unit,
    target_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, organization_id, rfq_id, source_request_item_id, line_number, item_name, description, quantity, unit, target_date, created_at, updated_at
`

type CreateRFQItemParams struct {
	OrganizationID      uuid.UUID      `json:"organization_id"`
	RfqID               uuid.UUID      `json:"rfq_id"`
	SourceRequestItemID *uuid.UUID     `json:"source_request_item_id"`
	LineNumber          int32          `json:"line_number"`
	ItemName            string         `json:"item_name"`
	Description         *string        `json:"description"`
	Quantity            pgtype.Numeric `json:"quantity"`
	Unit                string         `json:"unit"`
	TargetDate          pgtype.Date    `json:"target_date"`
}

func (q *Queries) CreateRFQItem(ctx context.Context, arg CreateRFQItemParams) (RfqItem, error) {
	row := q.db.QueryRow(ctx, createRFQItem,
		arg.OrganizationID,
		arg.RfqID,
		arg.SourceRequestItemID,
		arg.LineNumber,
		arg.ItemName,
		arg.Description,
		arg.Quantity,
		arg.Unit,
		arg.TargetDate,
	)
	var i RfqItem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RfqID,
		&i.SourceRequestItemID,
		&i.LineNumber,
		&i.ItemName,
		&i.Description,
		&i.Quantity,
		&i.Unit,
		&i.TargetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const evaluateRFQ = `-- name: EvaluateRFQ :one
UPDATE rfqs
SET
    status = 'evaluated',
    evaluated_at = now(),
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status = 'closed'
RETURNING id, organization_id, procurement_request_id, reference_number, title, description, status, created_by_user_id, published_at, closed_at, evaluated_at, cancelled_at, cancelled_by_user_id, created_at, updated_at
`

type EvaluateRFQParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) EvaluateRFQ(ctx context.Context, arg EvaluateRFQParams) (Rfq, error) {
	row := q.db.QueryRow(ctx, evaluateRFQ, arg.OrganizationID, arg.ID)
	var i Rfq
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProcurementRequestID,
		&i.ReferenceNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedByUserID,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.EvaluatedAt,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRFQByID = `-- name: GetRFQByID :one
SELECT id, organization_id, procurement_request_id, reference_number, title, description, status, created_by_user_id, published_at, closed_at, evaluated_at, cancelled_at, cancelled_by_user_id, created_at, updated_at
FROM rfqs
WHERE organization_id = $1
  AND id = $2
`

type GetRFQByIDParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetRFQByID(ctx context.Context, arg GetRFQByIDParams) (Rfq, error) {
	row := q.db.QueryRow(ctx, getRFQByID, arg.OrganizationID, arg.ID)
	var i Rfq
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProcurementRequestID,
		&i.ReferenceNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedByUserID,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.EvaluatedAt,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRFQItems = `-- name: ListRFQItems :many
SELECT id, organization_id, rfq_id, source_request_item_id, line_number, item_name, description, quantity, unit, target_date, created_at, updated_at
FROM rfq_items
WHERE organization_id = $1
  AND rfq_id = $2
ORDER BY line_number
`

type ListRFQItemsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	RfqID          uuid.UUID `json:"rfq_id"`
}

func (q *Queries) ListRFQItems(ctx context.Context, arg ListRFQItemsParams) ([]RfqItem, error) {
	rows, err := q.db.Query(ctx, listRFQItems, arg.OrganizationID, arg.RfqID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RfqItem{}
	for rows.Next() {
		var i RfqItem
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RfqID,
			&i.SourceRequestItemID,
			&i.LineNumber,
			&i.ItemName,
			&i.Description,
			&i.Quantity,
			&i.Unit,
			&i.TargetDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRFQVendors = `-- name: ListRFQVendors :many
SELECT rv.id, rv.organization_id, rv.rfq_id, rv.vendor_id, rv.attached_by_user_id, rv.attached_at, rv.created_at, v.name AS vendor_name, v.status AS vendor_status
FROM rfq_vendors AS rv
JOIN vendors AS v
    ON v.organization_id = rv.organization_id
   AND v.id = rv.vendor_id
WHERE rv.organization_id = $1
  AND rv.rfq_id = $2
ORDER BY v.name
`

type ListRFQVendorsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	RfqID          uuid.UUID `json:"rfq_id"`
}

type ListRFQVendorsRow struct {
	ID               uuid.UUID          `json:"id"`
	OrganizationID   uuid.UUID          `json:"organization_id"`
	RfqID            uuid.UUID          `json:"rfq_id"`
	VendorID         uuid.UUID          `json:"vendor_id"`
	AttachedByUserID uuid.UUID          `json:"attached_by_user_id"`
	AttachedAt       pgtype.Timestamptz `json:"attached_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	VendorName       string             `json:"vendor_name"`
	VendorStatus     VendorStatus       `json:"vendor_status"`
}

func (q *Queries) ListRFQVendors(ctx context.Context, arg ListRFQVendorsParams) ([]ListRFQVendorsRow, error) {
	rows, err := q.db.Query(ctx, listRFQVendors, arg.OrganizationID, arg.RfqID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRFQVendorsRow{}
	for rows.Next() {
		var i ListRFQVendorsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RfqID,
			&i.VendorID,
			&i.AttachedByUserID,
			&i.AttachedAt,
			&i.CreatedAt,
			&i.VendorName,
			&i.VendorStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRFQs = `-- name: ListRFQs :many
SELECT id, organization_id, procurement_request_id, reference_number, title, description, status, created_by_user_id, published_at, closed_at, evaluated_at, cancelled_at, cancelled_by_user_id, created_at, updated_at
FROM rfqs
WHERE organization_id = $1
  AND (
      $2::rfq_status IS NULL
      OR status = $2::rfq_status
  )
ORDER BY created_at DESC
`

type ListRFQsParams struct {
	OrganizationID uuid.UUID     `json:"organization_id"`
	Status         NullRfqStatus `json:"status"`
}

func (q *Queries) ListRFQs(ctx context.Context, arg ListRFQsParams) ([]Rfq, error) {
	rows, err := q.db.Query(ctx, listRFQs, arg.OrganizationID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rfq{}
	for rows.Next() {
		var i Rfq
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProcurementRequestID,
			&i.ReferenceNumber,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedByUserID,
			&i.PublishedAt,
			&i.ClosedAt,
			&i.EvaluatedAt,
			&i.CancelledAt,
			&i.CancelledByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRFQAwarded = `-- name: MarkRFQAwarded :one
UPDATE rfqs
SET
    status = 'awarded',
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status = 'evaluated'
RETURNING id, organization_id, procurement_request_id, reference_number, title, description, status, created_by_user_id, published_at, closed_at, evaluated_at, cancelled_at, cancelled_by_user_id, created_at, updated_at
`

type MarkRFQAwardedParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) MarkRFQAwarded(ctx context.Context, arg MarkRFQAwardedParams) (Rfq, error) {
	row := q.db.QueryRow(ctx, markRFQAwarded, arg.OrganizationID, arg.ID)
	var i Rfq
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProcurementRequestID,
		&i.ReferenceNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedByUserID,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.EvaluatedAt,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const publishRFQ = `-- name: PublishRFQ :one
UPDATE rfqs
SET
    status = 'published',
    published_at = now(),
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status = 'draft'
RETURNING id, organization_id, procurement_request_id, reference_number, title, description, status, created_by_user_id, published_at, closed_at, evaluated_at, cancelled_at, cancelled_by_user_id, created_at, updated_at
`

type PublishRFQParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) PublishRFQ(ctx context.Context, arg PublishRFQParams) (Rfq, error) {
	row := q.db.QueryRow(ctx, publishRFQ, arg.OrganizationID, arg.ID)
	var i Rfq
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProcurementRequestID,
		&i.ReferenceNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedByUserID,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.EvaluatedAt,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeVendorFromRFQ = `-- name: RemoveVendorFromRFQ :execrows
DELETE FROM rfq_vendors
WHERE organization_id = $1
  AND rfq_id = $2
  AND vendor_id = $3
`

type RemoveVendorFromRFQParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	RfqID          uuid.UUID `json:"rfq_id"`
	VendorID       uuid.UUID `json:"vendor_id"`
}

func (q *Queries) RemoveVendorFromRFQ(ctx context.Context, arg RemoveVendorFromRFQParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeVendorFromRFQ, arg.OrganizationID, arg.RfqID, arg.VendorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDraftRFQ = `-- name: UpdateDraftRFQ :one
UPDATE rfqs
SET
    reference_number = $3,
    title = $4,
    description = $5,
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
  AND status = 'draft'
RETURNING id, organization_id, procurement_request_id, reference_number, title, description, status, created_by_user_id, published_at, closed_at, evaluated_at, cancelled_at, cancelled_by_user_id, created_at, updated_at
`

type UpdateDraftRFQParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	ID              uuid.UUID `json:"id"`
	ReferenceNumber *string   `json:"reference_number"`
	Title           string    `json:"title"`
	Description     *string   `json:"description"`
}

func (q *Queries) UpdateDraftRFQ(ctx context.Context, arg UpdateDraftRFQParams) (Rfq, error) {
	row := q.db.QueryRow(ctx, updateDraftRFQ,
		arg.OrganizationID,
		arg.ID,
		arg.ReferenceNumber,
		arg.Title,
		arg.Description,
	)
	var i Rfq
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProcurementRequestID,
		&i.ReferenceNumber,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedByUserID,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.EvaluatedAt,
		&i.CancelledAt,
		&i.CancelledByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
