// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vendors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const archiveVendor = `-- name: ArchiveVendor :one
UPDATE vendors
SET
    status = 'archived',
    archived_at = now(),
    updated_by_user_id = $3,
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
RETURNING id, organization_id, name, legal_name, contact_name, email, phone, tax_identifier, address_line1, address_line2, city, state_region, postal_code, country, notes, status, archived_at, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type ArchiveVendorParams struct {
	OrganizationID  uuid.UUID  `json:"organization_id"`
	ID              uuid.UUID  `json:"id"`
	UpdatedByUserID *uuid.UUID `json:"updated_by_user_id"`
}

func (q *Queries) ArchiveVendor(ctx context.Context, arg ArchiveVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, archiveVendor, arg.OrganizationID, arg.ID, arg.UpdatedByUserID)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.LegalName,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.TaxIdentifier,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.StateRegion,
		&i.PostalCode,
		&i.Country,
		&i.Notes,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (
    organization_id,
    name,
    legal_name,
    contact_name,
    email,
    phone,
    tax_identifier,
    address_line1,
    address_line2,
    city,
    state_region,
    postal_code,
    country,
    notes,
    created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, organization_id, name, legal_name, contact_name, email, phone, tax_identifier, address_line1, address_line2, city, state_region, postal_code, country, notes, status, archived_at, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type CreateVendorParams struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	Name            string    `json:"name"`
	LegalName       *string   `json:"legal_name"`
	ContactName     *string   `json:"contact_name"`
	Email           *string   `json:"email"`
	Phone           *string   `json:"phone"`
	TaxIdentifier   *string   `json:"tax_identifier"`
	AddressLine1    *string   `json:"address_line1"`
	AddressLine2    *string   `json:"address_line2"`
	City            *string   `json:"city"`
	StateRegion     *string   `json:"state_region"`
	PostalCode      *string   `json:"postal_code"`
	Country         *string   `json:"country"`
	Notes           *string   `json:"notes"`
	CreatedByUserID uuid.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, createVendor,
		arg.OrganizationID,
		arg.Name,
		arg.LegalName,
		arg.ContactName,
		arg.Email,
		arg.Phone,
		arg.TaxIdentifier,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.StateRegion,
		arg.PostalCode,
		arg.Country,
		arg.Notes,
		arg.CreatedByUserID,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.LegalName,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.TaxIdentifier,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.StateRegion,
		&i.PostalCode,
		&i.Country,
		&i.Notes,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorByID = `-- name: GetVendorByID :one
SELECT id, organization_id, name, legal_name, contact_name, email, phone, tax_identifier, address_line1, address_line2, city, state_region, postal_code, country, notes, status, archived_at, created_by_user_id, updated_by_user_id, created_at, updated_at
FROM vendors
WHERE organization_id = $1
  AND id = $2
`

type GetVendorByIDParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetVendorByID(ctx context.Context, arg GetVendorByIDParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByID, arg.OrganizationID, arg.ID)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.LegalName,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.TaxIdentifier,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.StateRegion,
		&i.PostalCode,
		&i.Country,
		&i.Notes,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVendors = `-- name: ListVendors :many
SELECT id, organization_id, name, legal_name, contact_name, email, phone, tax_identifier, address_line1, address_line2, city, state_region, postal_code, country, notes, status, archived_at, created_by_user_id, updated_by_user_id, created_at, updated_at
FROM vendors
WHERE organization_id = $1
  AND (
      $2::vendor_status IS NULL
      OR status = $2::vendor_status
  )
ORDER BY created_at DESC
`

type ListVendorsParams struct {
	OrganizationID uuid.UUID        `json:"organization_id"`
	Status         NullVendorStatus `json:"status"`
}

func (q *Queries) ListVendors(ctx context.Context, arg ListVendorsParams) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, listVendors, arg.OrganizationID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.LegalName,
			&i.ContactName,
			&i.Email,
			&i.Phone,
			&i.TaxIdentifier,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.StateRegion,
			&i.PostalCode,
			&i.Country,
			&i.Notes,
			&i.Status,
			&i.ArchivedAt,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVendors = `-- name: SearchVendors :many
SELECT id, organization_id, name, legal_name, contact_name, email, phone, tax_identifier, address_line1, address_line2, city, state_region, postal_code, country, notes, status, archived_at, created_by_user_id, updated_by_user_id, created_at, updated_at
FROM vendors
WHERE organization_id = $1
  AND (
      lower(name) LIKE '%' || lower($2) || '%'
      OR lower(COALESCE(legal_name, '')) LIKE '%' || lower($2) || '%'
      OR lower(COALESCE(email, '')) LIKE '%' || lower($2) || '%'
  )
ORDER BY name
`

type SearchVendorsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Search         string    `json:"search"`
}

func (q *Queries) SearchVendors(ctx context.Context, arg SearchVendorsParams) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, searchVendors, arg.OrganizationID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.LegalName,
			&i.ContactName,
			&i.Email,
			&i.Phone,
			&i.TaxIdentifier,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.StateRegion,
			&i.PostalCode,
			&i.Country,
			&i.Notes,
			&i.Status,
			&i.ArchivedAt,
			&i.CreatedByUserID,
			&i.UpdatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendor = `-- name: UpdateVendor :one
UPDATE vendors
SET
    name = $3,
    legal_name = $4,
    contact_name = $5,
    email = $6,
    phone = $7,
    tax_identifier = $8,
    address_line1 = $9,
    address_line2 = $10,
    city = $11,
    state_region = $12,
    postal_code = $13,
    country = $14,
    notes = $15,
    updated_by_user_id = $16,
    updated_at = now()
WHERE organization_id = $1
  AND id = $2
RETURNING id, organization_id, name, legal_name, contact_name, email, phone, tax_identifier, address_line1, address_line2, city, state_region, postal_code, country, notes, status, archived_at, created_by_user_id, updated_by_user_id, created_at, updated_at
`

type UpdateVendorParams struct {
	OrganizationID  uuid.UUID  `json:"organization_id"`
	ID              uuid.UUID  `json:"id"`
	Name            string     `json:"name"`
	LegalName       *string    `json:"legal_name"`
	ContactName     *string    `json:"contact_name"`
	Email           *string    `json:"email"`
	Phone           *string    `json:"phone"`
	TaxIdentifier   *string    `json:"tax_identifier"`
	AddressLine1    *string    `json:"address_line1"`
	AddressLine2    *string    `json:"address_line2"`
	City            *string    `json:"city"`
	StateRegion     *string    `json:"state_region"`
	PostalCode      *string    `json:"postal_code"`
	Country         *string    `json:"country"`
	Notes           *string    `json:"notes"`
	UpdatedByUserID *uuid.UUID `json:"updated_by_user_id"`
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, updateVendor,
		arg.OrganizationID,
		arg.ID,
		arg.Name,
		arg.LegalName,
		arg.ContactName,
		arg.Email,
		arg.Phone,
		arg.TaxIdentifier,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.StateRegion,
		arg.PostalCode,
		arg.Country,
		arg.Notes,
		arg.UpdatedByUserID,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.LegalName,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.TaxIdentifier,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.StateRegion,
		&i.PostalCode,
		&i.Country,
		&i.Notes,
		&i.Status,
		&i.ArchivedAt,
		&i.CreatedByUserID,
		&i.UpdatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
